name: CI

on: [push, pull_request]

jobs:
  spellr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec ruby bin/spellr_workflow.rb
