name: CI

on: [push, pull_request]

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', 3.1, ruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec rspec

  rspec_no_did_you_mean:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec --tag ~did_you_mean
      env:
        DID_YOU_MEAN: '0'

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: gem install did_you_mean; COVERAGE=1 bundle exec rspec

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: 'coverage/*'
          retention-days: 1
        if: ${{ failure() }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec rubocop

  spellr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec ruby bin/spellr_workflow.rb

  leftovers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec leftovers

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: gem install did_you_mean; bundle exec rake build

